eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9090
spring:
  application:
    name: SIS_API_GATEWAY
  cloud:
    gateway:
      routes:
      - id: SIS-SERVICE-AUTH
        uri: lb://SERVICE-EXPLORER
        predicates:
           - Path=/auth/**
           
      - id: SIS-SERVICE-ADMINISTRATOR
        uri: lb://SERVICE-ADMINISTRATOR
        predicates:
           - Path=/admin/**
      
      - id: SIS-SERVICE-STUDENT
        uri: lb://SERVICE-STUDENT
        predicates:
           - Path=/user/**
           
           
           
           